17-03-03 17:23:23 - Modelo Persona - ERROR 
 'tuple' object is not callable
